inherit_from: .rubocop_todo.yml

require:
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-thread_safety

AllCops:
  NewCops: enable

  Exclude:
    - db/migrate/*
    - db/schema.rb
    - tmp/**/*
    - vendor/**/*

  TargetRubyVersion: 3.3

  DisplayCopNames: true

Rails:
  Enabled: true

Rails/I18nLocaleTexts:
  Enabled: false

Rails/Output:
  Include:
    - app/**/*.rb
    - config/**/*.rb
    - spec/**/*.rb
    - test/**/*.rb

# We encourage `find_by_id!` (an alias for `find`), as it's more explicit that it's using raw IDs (not HashIDs).
Rails/DynamicFindBy:
  Whitelist: find_by_id! find_by_hashid find_by_hashid!

RSpec/DescribeClass:
  Exclude:
    - spec/requests/**/*
    - spec/features/**/*

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/NamedSubject:
  Enabled: false

# Avoid checking for top-level documentation
Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  Exclude:
    - 'config/environments/*.rb'
    - 'config/routes.rb'
    - 'Guardfile'
    - 'spec/**/*'
    - 'lib/**/*'
    - 'test/**/*'

Layout/LineLength:
  Max: 200

Metrics/ClassLength:
  Exclude:
    - 'test/**/*' # permit long test files!

Metrics/MethodLength:
  Max: 20

# Allow short (2-letter) param names
Naming/MethodParameterName:
  Enabled: false
