services:
  db:
    image: postgis/postgis:latest
    ports:
      - 5432:5432
    env_file:
      - .env
  app:
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: ./entrypoint
    depends_on:
      - db
    volumes:
      - ./:/usr/app/landgrab
    ports:
      - 3000:3000
