<% if ENV.key?('ACTIVE_STORAGE_SERVICE_PROVIDER') %>
local:
  service: <%= ENV.fetch('ACTIVE_STORAGE_SERVICE_PROVIDER').downcase.to_sym %>
<% else %>
local:
  service: Disk
  root: <%= Rails.root.join('storage') %>
<% end %>
