cloudinary:
  service: Cloudinary
s3:
  service: S3
  endpoint: <%= ENV.fetch('ACTIVE_STORAGE_S3_ENDPOINT', nil) %>
  access_key_id: <%= ENV.fetch('ACTIVE_STORAGE_S3_ACCESS_KEY_ID', nil) %>
  secret_access_key: <%= ENV.fetch('ACTIVE_STORAGE_S3_SECRET_ACCESS_KEY', nil) %>
  bucket: <%= ENV.fetch('ACTIVE_STORAGE_S3_BUCKET_NAME', nil) %>
  region: <%= ENV.fetch('ACTIVE_STORAGE_S3_REGION', nil) %>
  request_checksum_calculation: when_required
  response_checksum_validation: when_required
  public: true
