<% case ENV.fetch('ACTIVE_STORAGE_SERVICE_PROVIDER', nil)&.downcase&.to_sym %>
<% when nil %>
<% when :cloudinary %>
cloudinary:
  service: :cloudinary
<% when :s3 %>
s3:
  service: S3
  endpoint: <%= ENV.fetch('ACTIVE_STORAGE_S3_ENDPOINT') %>
  access_key_id: <%= ENV.fetch('ACTIVE_STORAGE_S3_ACCESS_KEY_ID') %>
  secret_access_key: <%= ENV.fetch('ACTIVE_STORAGE_S3_SECRET_ACCESS_KEY') %>
  bucket: <%= ENV.fetch('ACTIVE_STORAGE_S3_BUCKET_NAME') %>
  region: <%= ENV.fetch('ACTIVE_STORAGE_S3_REGION') %>
  request_checksum_calculation: when_required
  response_checksum_validation: when_required
  public: true
<% end %>
